### ISSUE TITLE
Doesn't work with VST SDK 3.8.0

### ISSUE THREAD

**Issue by russellmcc** [coupler-rs/vst3-rs#20]
VST SDK 3.8.0 added forward-declared external C structs for the first time (for wayland support),

now this crate fails with errors like:

```
error[E0412]: cannot find type `xdg_toplevel` in this scope
    --> /Users/russruss/proj/sdks/vst3-rs/target/debug/build/vst3-df5410d317aec359/out/bindings.rs:1378:23
     |
1378 |             ) -> *mut xdg_toplevel
     |                       ^^^^^^^^^^^^ not found in this scope
```

This is because `xdg_toplevel` isn't defined so we don't parse the record definition.
